select * from [DsSix_customer]
select * from [DsSix_employee]
select ["ProductID"], count(["ItemSize"]) from [DsSix_inventoryItem] group by ["ProductID"]
select * From [DsSix_ItemSize]
select * From [DsSix_Manufacturer]
select * From [DsSix_Purchase]
select * From [DsSix_product]
select  * From [DsSix_PurchaseItem]
select * From [DsSix_SalaryEmployee]
select * From [DsSix_Sale]
select * From [DsSix_SaleItem]
select * From [DsSix_WageEmployee]

